micronaut:
  application:
    name: micronaut-jpa-cache
  server:
        port: 8084
  router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
  caches:
    cameras-by-country-and-installation:
      maximumSize:2000000
    cameras-by-country-and-installation-and-zone:
      maximumSize:2000000
    cameras-by-serial:
      maximumSize:2000000
    cameras-all:
      maximumSize:2000000
    cameras-all-keys:
      maximumSize:2000000
    voss-by-country-and-installation:
      maximumSize:2000000
    voss-all:
      maximumSize:2000000

datasources:
  default:
    type: com.zaxxer.hikari.HikariDataSource 
    url: jdbc:oracle:thin:@es1prerac03-scan:1521/PROTMPRE_SRV.sp.securitasdirect.local
    username: RS_SCORR
    password: RS_SCORR
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 200
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 3000
      leak-detection-threshold: 0
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true


        
                 
              