micronaut:
  application:
    name: multicache
  server:
        port: 8084
  router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
jpa:
    default:
        packages-to-scan:
            - 'com.msl.micronaut.domain.entity' 
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true
application:
    max: 50                
              